spring:
     cloud:
          gateway:
               routes:
                    -    id: user-service-users
                         uri: lb://user-service
                         predicates:
                              - Path=/api/v1/users/**
                         filters:
                              - StripPrefix=0
                    -    id: user-service-roles
                         uri: lb://user-service
                         predicates:
                              - Path=/api/v1/roles/**
                         filters:
                              - StripPrefix=0
                    -    id: organization-service
                         uri: lb://organization-service
                         predicates:
                              - Path=/api/v1/organizations/**
                         filters:
                              - StripPrefix=0
management:
     endpoints:
          web:
               exposure:
                    include: health,info,gateway,refresh
logging:
     level:
          org.springframework.cloud.gateway: INFO
          com.fincomply: INFO