spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: -Path=/api/v1/users/**
          filters: -StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.fincomply: INFO
