server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
api-gateway:
  message: "Welcome to FinComply API Gateway - QA Environment"
