server:
     port: 9000
spring:
     datasource:
          url: jdbc:mysql://localhost:3306/orgdbdev
          username: admin
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
     jpa:
          hibernate:
               ddl-auto: update
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
          open-in-view: false

organization-service:
     message: "Welcome to FinComply Organization-Service related Dev Environment APIs"
     contactDetails:
          name: "Shahajahan Ahamed - Developer"
          email: "ahamedshahajahan@gmail.com"
     onCallSupport:
          - "+91 9832973455"
          - "+91 9875319606"
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus
