server:
     port: 9001
spring:
     datasource:
          url: jdbc:postgresql://localhost:5432/orgdbqa
          username: admin
          password: secret
          driver-class-name: org.postgresql.Driver
     jpa:
          hibernate:
               ddl-auto: validate
          show-sql: true
          properties:
               hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
                    format_sql: true
          open-in-view: false
organization-service:
     message: "Welcome to FinComply Organization-Service related QA Environment APIs"
     contactDetails:
          name: "QA Support"
          email: "ahamedshahajahan@gmail.com"
     onCallSupport:
          - "+91 9832973455"
          - "+91 9875319606"
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus