server:
     port: 9002
spring:
     datasource:
          url: jdbc:postgresql://localhost:5432/orgdbprod
          username: admin
          password: secret
     jpa:
          hibernate:
               ddl-auto: update #validate for dev/qa to ensure schema alignment, none for prod to prevent changes
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus
organization-service:
     message: "Welcome to FinComply Organization-Service related Production Environment APIs "
     contactDetails:
          name: "Production Support"
          email: "prod-support@fincomply.com"
     onCallSupport:
          - "+91 9222222222"
          - "+91 9333333333"