spring:
     application:
          name: organization-service
     datasource:
          driver-class-name: org.postgresql.Driver
     jpa:
          hibernate:
               ddl-auto: validate #for dev/qa to ensure schema alignment, none for prod to prevent changes
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
     flyway:
          enabled: true
          locations: classpath:db/migration
eureka:
     client:
          serviceUrl:
               defaultZone: http://localhost:8761/eureka
          register-with-eureka: true
          fetch-registry: true
     instance:
          prefer-ip-address: true

resilience4j:
     circuitbreaker:
          instances:
               organization-service:
                    slidingWindowSize: 10
                    failureRateThreshold: 50
                    waitDurationInOpenState: 10s
                    permittedNumberOfCallsInHalfOpenState: 3
                    registerHealthIndicator: true
     retry:
          instances:
               organization-service:
                    maxAttempts: 3
                    waitDuration: 1s
                    retryExeptions:
                         - feign.FeignException$InternalServerError
                         - feign.FeignException$ServiceUnavailable
                         - feign.FeignException$GatewayTimeout
     bulkhead:
          instances:
               organization-service:
                    maxConcurrentCalls: 10
                    maxWaitDuration: 1s
     timelimiter:
          instances:
               organization-service:
                    timeoutDuration: 2s
                    cancelRunningFuture: true
feign:
     client:
          config:
               organization-service:
                    connectTimeout: 10000
                    readTimeout: 10000
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus
     endpoint:
          refresh:
               enabled: true
          prometheus:
               enabled: true
     tracing:
          enabled: true
          sampling:
               probability: 1
logging:
     level:
          root: INFO
          org.springframework.cloud.gateway: INFO
          com.fincomply: INFO
     pattern:
          console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%traceId/%spanId] %-5level %logger{36} - %msg%n"
build:
     version: "1.0"

user-service:
     base-url: http://user-service/api/v1