server:
     port: 9001
spring:
     datasource:
          url: jdbc:postgresql://localhost:5432/orgdbqa
          username: admin
          password: secret
     jpa:
          hibernate:
               ddl-auto: update #validate for dev/qa to ensure schema alignment, none for prod to prevent changes
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh
organization-service:
     message: "Welcome to FinComply Organization-Service related QA Environment APIs "
     contactDetails:
          name: "QA Support"
          email: "ahamedshahajahan@gmail.com"
     onCallSupport:
          - +91 9832973455
          - +91 9875319606