server:
     port: 9000
spring:
     datasource:
          url: jdbc:postgresql://localhost:5433/orgdbdev
          username: admin
          password: secret
          driver-class-name: org.postgresql.Driver
     jpa:
          hibernate:
               ddl-auto: update
          show-sql: true
          properties:
               hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
                    format_sql: true
          open-in-view: false
     kafka:
          bootstrap-servers: localhost:5000  # Changed to host-mapped port
          producer:
               key-serializer: org.apache.kafka.common.serialization.StringSerializer
               value-serializer: org.apache.kafka.common.serialization.StringSerializer
          admin:
               auto-create: true  # Enable for dev
app:
     topics:
          organization-events: organization-events
organization-service:
     message: "Welcome to FinComply Organization-Service related Dev Environment APIs"
     contactDetails:
          name: "Shahajahan Ahamed - Developer"
          email: "ahamedshahajahan@gmail.com"
     onCallSupport:
          - "+91 9832973455"
          - "+91 9875319606"
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus