spring:
     application:
          name: organization-service
     datasource:
          driver-class-name: org.postgresql.Driver
     jpa:
          hibernate:
               ddl-auto: update #validate for dev/qa to ensure schema alignment, none for prod to prevent changes
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
#     flyway:
#          enabled: true
#          locations: classpath:db/migration
eureka:
     client:
          serviceUrl:
               defaultZone: http://localhost:8761/eureka
          register-with-eureka: true
          fetch-registry: true
     instance:
          prefer-ip-address: true
management:
     endpoints:
          exposure:
               include: health,info,metrics,refresh
     endpoint:
          refresh:
               enabled: true
logging:
     level:
          org.springframework.cloud.gateway: INFO
          com.fincomply: INFO
build:
     version: 1.0