server:
     port: 9000

spring:
     datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://user-db:5432/userdb
          username: admin
          password: secret
     jpa:
          hibernate:
               ddl-auto: validate
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
build:
     version: "1.0"

user-service:
     message: "Welcome to FinComply User-Service related docker APIs "
     contactDetails:
          name: "Shahajahan Ahamed- Developer"
          email: "ahamedshahajahan@gmail.com"
     onCallSupport:
          - +91 9832973455
          - +91 9875319606