server:
     port: 9000

spring:
     datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://user-db:5432/userdb
          username: admin
          password: secret
     jpa:
          hibernate:
               ddl-auto: validate
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
