server:
  port: 9011
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdbprod
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,prometheus
  endpoint:
    health:
      show-details: always
user-service:
  message: "Welcome to FinComply User-Service related Production Environment APIs "
  contactDetails:
    name: "Production Support"
    email: "prod-support@fincomply.com"
  onCallSupport:
    - "+91 9222222222"
    - "+91 9333333333"
