server:
     port: 9003

spring:
     datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://user-db-server:5432/userproddb
          username: admin
          password: secret

user-service:
     message: "Welcome to FinComply User-Service related Production Environment APIs "
     contactDetails:
          name: "Production Support"
          email: "prod-support@fincomply.com"
     onCallSupport:
          - "+91 9222222222"
          - "+91 9333333333"
