server:
  port: 9012
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdbqa
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
user-service:
  message: "Welcome to FinComply User-Service related QA Environment APIs "
  contactDetails:
    name: "QA Support"
    email: "qa-support@fincomply.com"
  onCallSupport:
    - "+91 9832973455"
    - "+91 9875319606"
