server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userdbdev
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    database-type: POSTGRESQL
build:
  version: "1.0"
user-service:
  message: "Welcome to FinComply User-Service related Dev Environment APIs "
  contactDetails:
    name: "Shahajahan Ahamed- Developer"
    email: "ahamedshahajahan@gmail.com"
  onCallSupport:
    - +91 9832973455
    - +91 9875319606
