spring:
     application:
          name: user-service
     datasource:
          driver-class-name: org.postgresql.Driver
     jpa:
          hibernate:
          ddl-auto: validate #for dev/qa to ensure schema alignment, none for prod to prevent changes
          show-sql: true
          properties:
               hibernate:
                    format_sql: true
     flyway:
          enabled: true
          locations: classpath:db/migration
eureka:
     client:
          serviceUrl:
               defaultZone: http://localhost:8761/eureka
          register-with-eureka: true
          fetch-registry: true
     instance:
          prefer-ip-address: true


resilience4j:
     circuitbreaker:
          instances:
               user-service:
                    slidingWindowSize: 10
                    failureRateThreshold: 50
                    waitDurationInOpenState: 10s
                    permittedNumberOfCallsInHalfOpenState: 3
                    registerHealthIndicator: true
     retry:
          instances:
               user-service:
                    maxAttempts: 3
                    waitDuration: 1s
                    retryExeptions:
                         - feign.FeignException$InternalServerError
                         - feign.FeignException$ServiceUnavailable
                         - feign.FeignException$GatewayTimeout
     bulkhead:
          instances:
               user-service:
                    maxConcurrentCalls: 10
                    maxWaitDuration: 1s
     timelimiter:
          instances:
               user-service:
                    timeoutDuration: 2s
                    cancelRunningFuture: true
feign:
     client:
          config:
               user-service:
                    connectTimeout: 2000
                    readTimeout: 2000

management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,refresh,prometheus
     endpoint:
          refresh:
               enabled: true
logging:
     level:
          com.fincomply: INFO
build:
     version: "1.0"

organization-service:
     url: http://organization-service/api/v1
